name: Bundle and Publish Sources

on:
  push:
    branches: [master]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v5
      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint project
        run: npm run lint
        continue-on-error: true
      - name: Run tests
        run: npm test ArcRelight && npm test AssortedScans
      - name: Generate bundle
        run: npm run bundle
      - name: Generate docs
        run: npm run docs
        continue-on-error: true
      - name: Upload bundle artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: bundles
  publish:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deploy.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
